language: node_js

node_js:
  - 16

cache: npm

script:
  - sh .travis/install_dev.sh || travis_terminate 1;
  - sh .travis/tests_and_lint.sh || travis_terminate 1;

after_success:
  - sh .travis/deploy_dockerhub.sh || travis_terminate 1;
  - test “$TRAVIS_BRANCH” = “master” && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/deploy_heroku.sh;
