
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install packages
        run: ./scripts/install_deps.sh
      - name: Test and Lint
        run: ./scripts/test_and_lint.sh
      - name: Deploy to DockerHub
        run: ./scripts/deploy_dockerhub.sh
      - name: Deploy to Heroku
        run: ./scripts/deploy_heroku.sh
