
name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: pwd
        run: pwd
      - name: ls
        run: ls -a
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: /home/runner/work/portfolio-pwa/portfolio-pwa/package-lock.json
      - name: Install packages
        run: /.scripts/install_deps.sh
      - name: Test and Lint
        run: /.scripts/test_and_lint.sh
      - name: Deploy to DockerHub
        run: /.scripts/deploy_dockerhub.sh
      - name: Deploy to Heroku
        run: /.scripts/deploy_heroku.sh
