
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install packages
        run: |
          chmod +x .scripts/install_deps.sh
          .scripts/install_deps.sh
        shell: bash
      - name: Test and Lint
        run: |
          chmod +x .scripts/test_and_lint.sh
          .scripts/test_and_lint.sh
        shell: bash
      - name: Deploy to DockerHub
        run: |
          chmod +x .scripts/deploy_dockerhub.sh
          .scripts/deploy_dockerhub.sh
        shell: bash
      - name: Deploy to Heroku
        run: |
          chmod +x .scripts/deploy_heroku.sh
          .scripts/deploy_heroku.sh
        shell: bash
